spring:
  datasource:
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger"

riot:
  apiKey: "Add your development key"

# Remove Jooq Advert
logging:
  level:
    org:
      jooq:
        Constants: off